name: Test Program

on:
  push:
    branches: 
      - main
    paths:
      - '**.py'
      - 'app/**'
      - 'tests/**'
      - 'requirements.txt'
  pull_request:
    branches: 
      - main
    paths:
      - '**.py'
      - 'app/**'
      - 'tests/**'
      - 'requirements.txt'

jobs:
  backend:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.11.0"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        apt-get update && apt-get install libgl1
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest --capture=sys --verbose tests
