name: Tests

on:
  push:
    branches: 
      - main
    paths:
      - '**.py'
      - 'app/**'
      - 'tests/**'
      - 'requirements.txt'
  pull_request:
    branches: 
      - main
    paths:
      - '**.py'
      - 'app/**'
      - 'tests/**'
      - 'requirements.txt'

jobs:
  backend:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.11.0"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.4
    - name: Fix Qt plugin issues
      run: |
        sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
        export QT_QPA_PLATFORM=offscreen
    - name: Test with pytest
      run: |
        pytest --capture=sys --verbose tests